// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5kqvUmhSJi8gmXR57XswO-7tYj7fwRv0',
    appId: '1:859327578614:web:ec3956f48d3d091047c7d7',
    messagingSenderId: '859327578614',
    projectId: 'chat-tunify-eb3dc',
    authDomain: 'chat-tunify-eb3dc.firebaseapp.com',
    storageBucket: 'chat-tunify-eb3dc.appspot.com',
    databaseURL: 'https://chat-tunify-eb3dc-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rcdKToLFftEyBLa2Em1CB0ljJNAMlNs',
    appId: '1:859327578614:android:9040309ff736573047c7d7',
    messagingSenderId: '859327578614',
    projectId: 'chat-tunify-eb3dc',
    storageBucket: 'chat-tunify-eb3dc.appspot.com',
    databaseURL: 'https://chat-tunify-eb3dc-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUZ5xrxnjEZfKlX1n4CzOj5_tqJ8s6N8',
    appId: '1:859327578614:ios:eb28618716fa75f347c7d7',
    messagingSenderId: '859327578614',
    projectId: 'chat-tunify-eb3dc',
    storageBucket: 'chat-tunify-eb3dc.appspot.com',
    iosBundleId: 'com.woozu.chatTunify',
    databaseURL: 'https://chat-tunify-eb3dc-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUZ5xrxnjEZfKlX1n4CzOj5_tqJ8s6N8',
    appId: '1:859327578614:ios:2a1ba833d664affa47c7d7',
    messagingSenderId: '859327578614',
    projectId: 'chat-tunify-eb3dc',
    storageBucket: 'chat-tunify-eb3dc.appspot.com',
    iosBundleId: 'com.woozu.chatTunify.RunnerTests',
    databaseURL: 'https://chat-tunify-eb3dc-default-rtdb.firebaseio.com/',
  );
}
